// <auto-generated />
using Ligia_Hui.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ligia_Hui.Migrations
{
    [DbContext(typeof(Ligia_HuiContext))]
    partial class Ligia_HuiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ligia_Hui.Models.Departament", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("dep")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("ID");

                    b.ToTable("Departament");
                });

            modelBuilder.Entity("Ligia_Hui.Models.DepMag", b =>
                {
                    b.Property<int>("DepMagID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartamentID");

                    b.Property<int>("MagazinID");

                    b.Property<int>("ProdusID");

                    b.HasKey("DepMagID");

                    b.HasIndex("DepartamentID");

                    b.HasIndex("MagazinID");

                    b.ToTable("DepMag");
                });

            modelBuilder.Entity("Ligia_Hui.Models.Magazin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("mag")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("ID");

                    b.ToTable("Magazin");
                });

            modelBuilder.Entity("Ligia_Hui.Models.Produs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartamentID");

                    b.Property<int>("MagazinID");

                    b.Property<string>("numeangajat")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("post")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("ID");

                    b.HasIndex("DepartamentID");

                    b.HasIndex("MagazinID");

                    b.ToTable("Produs");
                });

            modelBuilder.Entity("Ligia_Hui.Models.DepMag", b =>
                {
                    b.HasOne("Ligia_Hui.Models.Departament", "Departament")
                        .WithMany()
                        .HasForeignKey("DepartamentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ligia_Hui.Models.Magazin", "Magazin")
                        .WithMany("DepMag")
                        .HasForeignKey("MagazinID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ligia_Hui.Models.Produs", b =>
                {
                    b.HasOne("Ligia_Hui.Models.Departament", "Departament")
                        .WithMany("Produs")
                        .HasForeignKey("DepartamentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ligia_Hui.Models.Magazin", "Magazin")
                        .WithMany()
                        .HasForeignKey("MagazinID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
